# Generated by Django 3.2.9 on 2021-11-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Posteo', 'verbose_name_plural': 'Posteos'},
        ),
    ]
